int x;
x = 10;
Console.WriteLine(x);
x = 20;
Console.WriteLine(x);
x = x + 5;
Console.WriteLine(x);
x++;
Console.WriteLine(x);
x+=6;
Console.WriteLine(x);
x--;
Console.WriteLine(x);
x -= 3;
Console.WriteLine(x);
x = x * 2;
Console.WriteLine(x);
x *= 3;
Console.WriteLine(x);
x = x / 2;
Console.WriteLine(x);
x /= 3;
Console.WriteLine(x);
x = 17;
Console.WriteLine(x);
x /= 3;
Console.WriteLine(x);